version: '3.3'

services:

  nginx:
    image: nginx:${NGINX_IMAGE_TAG}
    restart: always
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    image: 01-java-web-app-frontend:${FRONTEND_IMAGE_TAG}
    build: ./frontend/
    restart: always
    depends_on:
      - backend

  backend:
    image: 01-java-web-app-backend:${BACKEND_IMAGE_TAG}
    build: ./backend/
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://${BACKEND_DB_HOST}:3306/${BACKEND_DB_NAME}'
      SPRING_DATASOURCE_USERNAME: '${BACKEND_DB_USER}'
      SPRING_DATASOURCE_PASSWORD: '${BACKEND_DB_PASS}'
    depends_on:
      - db
  
  db:
    image: mysql:${MYSQL_IMAGE_TAG}
    restart: always
    environment:
      MYSQL_DATABASE: '${BACKEND_DB_NAME}'
      MYSQL_USER: '${BACKEND_DB_USER}'
      MYSQL_PASSWORD: '${BACKEND_DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${BACKEND_DB_PASS}'
    volumes:
      - ${PWD}/mysql:/var/lib/mysql